---
deployment:
  tasks:
    - echo "== START =="; date
    - export DEPLOYPATH=/home/ttm87d594aro/public_html/flip_test_isa
    - echo "== mkdir =="; /bin/mkdir -p $DEPLOYPATH
    - echo "== npm ci/install =="; npm ci || npm install
    - echo "== build =="; npm run build
    - echo "== clear =="; /bin/rm -rf $DEPLOYPATH/*
    - echo "== copy dist =="; /bin/cp -R dist/* $DEPLOYPATH/
    - echo "== DONE =="; date

